-- MySQL Script generated by MySQL Workbench
-- Mon Oct 19 09:55:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_gobook
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_gobook` ;

-- -----------------------------------------------------
-- Schema db_gobook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_gobook` DEFAULT CHARACTER SET utf8 ;
USE `db_gobook` ;

-- -----------------------------------------------------
-- Table `db_gobook`.`tb_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_autor` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_autor` (
  `id_autor` INT NOT NULL AUTO_INCREMENT,
  `nm_autor` VARCHAR(200) NULL,
  `ds_img` VARCHAR(100) NULL,
  `ds_genero` VARCHAR(45) NULL,
  `dt_nascimento` DATETIME NULL,
  `ds_autor` VARCHAR(400) NULL,
  `bt_filiado` TINYINT NULL,
  PRIMARY KEY (`id_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_genero_principal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_genero_principal` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_genero_principal` (
  `id_genero_principal` INT NOT NULL AUTO_INCREMENT,
  `nm_genero` VARCHAR(100) NULL,
  PRIMARY KEY (`id_genero_principal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_ebook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_ebook` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_ebook` (
  `id_ebook` INT NOT NULL AUTO_INCREMENT,
  `id_autor` INT NOT NULL,
  `id_genero_principal` INT NOT NULL,
  `nm_ebook` VARCHAR(100) NULL,
  `ds_ebook` VARCHAR(400) NULL,
  `ds_img` VARCHAR(100) NULL,
  `vl_ebook` DECIMAL NULL,
  `qt_paginas` INT NULL,
  `nm_editora` VARCHAR(100) NULL,
  `ds_edicao` VARCHAR(45) NULL,
  `ds_cod_barra` VARCHAR(45) NULL,
  `ds_isbn` VARCHAR(13) NULL,
  `nm_lingua` VARCHAR(45) NULL,
  `nm_lingua_original` VARCHAR(45) NULL,
  `dt_insercao` DATETIME NULL,
  PRIMARY KEY (`id_ebook`),
  INDEX `fk_tb_ebook_tb_autor1_idx` (`id_autor` ASC) VISIBLE,
  INDEX `fk_tb_ebook_tb_genero_principal1_idx` (`id_genero_principal` ASC) VISIBLE,
  CONSTRAINT `fk_tb_ebook_tb_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `db_gobook`.`tb_autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_ebook_tb_genero_principal1`
    FOREIGN KEY (`id_genero_principal`)
    REFERENCES `db_gobook`.`tb_genero_principal` (`id_genero_principal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_login` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `ds_email` VARCHAR(200) NULL,
  `ds_senha` VARCHAR(30) NULL,
  `ds_perfil` VARCHAR(100) NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_endereco` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `ds_cep` VARCHAR(14) NULL,
  `ds_rua` VARCHAR(45) NULL,
  `nr_casa` INT NULL,
  `ds_complemento` VARCHAR(100) NULL,
  `ds_estado` VARCHAR(45) NULL,
  `ds_cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_usuario` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_login` INT NOT NULL,
  `id_endereco` INT NULL,
  `nm_usuario` VARCHAR(200) NULL,
  `ds_img` VARCHAR(100) NULL,
  `dt_nascimento` DATETIME NULL,
  `ds_cpf` VARCHAR(20) NULL,
  `ds_genero` VARCHAR(45) NULL,
  `bt_assinante` TINYINT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tb_usuario_tb_login_idx` (`id_login` ASC) VISIBLE,
  INDEX `fk_tb_usuario_tb_endereco1_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_tb_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `db_gobook`.`tb_login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_tb_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `db_gobook`.`tb_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_usuario_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_usuario_administrador` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_usuario_administrador` (
  `id_usuario_administrador` INT NOT NULL AUTO_INCREMENT,
  `id_login` INT NOT NULL,
  `id_endereco` INT NOT NULL,
  `nm_usuario` VARCHAR(200) NULL,
  `ds_img` VARCHAR(100) NULL,
  `ds_cargo` VARCHAR(100) NULL,
  `dt_nasc` DATETIME NULL,
  `ds_rg` VARCHAR(20) NULL,
  `ds_cpf` VARCHAR(20) NULL,
  `ds_genero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario_administrador`),
  INDEX `fk_tb_administrador_tb_login1_idx` (`id_login` ASC) VISIBLE,
  INDEX `fk_tb_administrador_tb_endereco1_idx` (`id_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_tb_administrador_tb_login1`
    FOREIGN KEY (`id_login`)
    REFERENCES `db_gobook`.`tb_login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_administrador_tb_endereco1`
    FOREIGN KEY (`id_endereco`)
    REFERENCES `db_gobook`.`tb_endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_venda` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `dt_compra` DATETIME NULL,
  `nr_nota_fiscal` INT NULL,
  `tp_pgto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_tb_compra_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_compra_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gobook`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_venda_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_venda_item` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_venda_item` (
  `id_venda_item` INT NOT NULL AUTO_INCREMENT,
  `id_ebook` INT NOT NULL,
  `id_venda` INT NOT NULL,
  `qt_itens` INT NULL,
  `ds_codigo_presente` VARCHAR(45) NULL,
  `bt_presente_ativo` TINYINT NULL,
  PRIMARY KEY (`id_venda_item`),
  INDEX `fk_tb_compra_item_tb_ebook1_idx` (`id_ebook` ASC) VISIBLE,
  INDEX `fk_tb_compra_item_tb_compra1_idx` (`id_venda` ASC) VISIBLE,
  CONSTRAINT `fk_tb_compra_item_tb_ebook1`
    FOREIGN KEY (`id_ebook`)
    REFERENCES `db_gobook`.`tb_ebook` (`id_ebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_compra_item_tb_compra1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `db_gobook`.`tb_venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_pgto_autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_pgto_autor` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_pgto_autor` (
  `id_pgto_autor` INT NOT NULL AUTO_INCREMENT,
  `id_autor` INT NOT NULL,
  `vl_pgto` DECIMAL NULL,
  `ds_ebooks` VARCHAR(200) NULL,
  `dt_pgto` DATETIME NULL,
  PRIMARY KEY (`id_pgto_autor`),
  INDEX `fk_tb_pagamento_autor_tb_autor1_idx` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pagamento_autor_tb_autor1`
    FOREIGN KEY (`id_autor`)
    REFERENCES `db_gobook`.`tb_autor` (`id_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_controle_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_controle_administrador` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_controle_administrador` (
  `id_controle_administrador` INT NOT NULL AUTO_INCREMENT,
  `id_login` INT NOT NULL,
  `dt_login` DATETIME NULL,
  PRIMARY KEY (`id_controle_administrador`),
  INDEX `fk_tb_controle_administrador_tb_login1_idx` (`id_login` ASC) VISIBLE,
  CONSTRAINT `fk_tb_controle_administrador_tb_login1`
    FOREIGN KEY (`id_login`)
    REFERENCES `db_gobook`.`tb_login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_cartao` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_cartao` (
  `id_cartao` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `tp_cartao` VARCHAR(1) NULL,
  `nm_bandeira` VARCHAR(45) NULL,
  `nm_titular` VARCHAR(200) NULL,
  `ds_cartao` VARCHAR(19) NULL,
  `dt_expira` DATETIME NULL,
  PRIMARY KEY (`id_cartao`),
  INDEX `fk_tb_cartao_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cartao_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gobook`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_pgto_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_pgto_usuario` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_pgto_usuario` (
  `id_pgto_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `dt_pgto` DATETIME NULL,
  PRIMARY KEY (`id_pgto_usuario`),
  INDEX `fk_tb_pgto_usuario_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pgto_usuario_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gobook`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_estante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_estante` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_estante` (
  `id_estante` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `ds_generos_fav` VARCHAR(200) NULL,
  PRIMARY KEY (`id_estante`),
  INDEX `fk_tb_estante_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_tb_estante_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gobook`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_estante_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_estante_item` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_estante_item` (
  `id_estante_item` INT NOT NULL AUTO_INCREMENT,
  `id_estante` INT NOT NULL,
  `id_ebook` INT NOT NULL,
  `bt_favorito` TINYINT NULL,
  PRIMARY KEY (`id_estante_item`),
  INDEX `fk_tb_estante_item_tb_ebook1_idx` (`id_ebook` ASC) VISIBLE,
  INDEX `fk_tb_estante_item_tb_estante1_idx` (`id_estante` ASC) VISIBLE,
  CONSTRAINT `fk_tb_estante_item_tb_ebook1`
    FOREIGN KEY (`id_ebook`)
    REFERENCES `db_gobook`.`tb_ebook` (`id_ebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_estante_item_tb_estante1`
    FOREIGN KEY (`id_estante`)
    REFERENCES `db_gobook`.`tb_estante` (`id_estante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_genero` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `id_ebook` INT NOT NULL,
  `nm_genero` VARCHAR(100) NULL,
  PRIMARY KEY (`id_genero`),
  INDEX `fk_tb_genero_tb_ebook1_idx` (`id_ebook` ASC) VISIBLE,
  CONSTRAINT `fk_tb_genero_tb_ebook1`
    FOREIGN KEY (`id_ebook`)
    REFERENCES `db_gobook`.`tb_ebook` (`id_ebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_gobook`.`tb_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_gobook`.`tb_feedback` ;

CREATE TABLE IF NOT EXISTS `db_gobook`.`tb_feedback` (
  `id_feedback` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_ebook` INT NOT NULL,
  `id_admin_aprovacao` INT NULL,
  `ds_feedback` VARCHAR(400) NULL,
  `qt_estrelas` INT NULL,
  `bt_aprovado` TINYINT NULL,
  PRIMARY KEY (`id_feedback`),
  INDEX `fk_tb_feedback_tb_ebook1_idx` (`id_ebook` ASC) VISIBLE,
  INDEX `fk_tb_feedback_tb_usuario1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_tb_feedback_tb_usuario_administrador1_idx` (`id_admin_aprovacao` ASC) VISIBLE,
  CONSTRAINT `fk_tb_feedback_tb_ebook1`
    FOREIGN KEY (`id_ebook`)
    REFERENCES `db_gobook`.`tb_ebook` (`id_ebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_feedback_tb_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_gobook`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_feedback_tb_usuario_administrador1`
    FOREIGN KEY (`id_admin_aprovacao`)
    REFERENCES `db_gobook`.`tb_usuario_administrador` (`id_usuario_administrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
